### PR TITLE
upgrade passport version to 0.6 and fix regenerate error

### LINKED ISSUE #10: Passport version 0.6 not compatible with current express-session package
**Describe the bug**
 When upgrading Passport version to 0.6, it will throw "req.session.regenerate is not a function".

**To Reproduce**
update passport version from 0.5.3 to 0.6.0(newest)

**Expected behavior**
Throw "req.session.regenerate is not a function" error whenever authentication is required.

passporterror

### PR DESCRIPTION
**Pull request by Neuroleptique**
# Description

Upgrade passport version to the latest to patch [CVE-2022-25896](https://github.com/advisories/GHSA-v923-w3x8-wh69) vulnerability.

Fixes #10 

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)

### CODE REVIEW

**Comment by Neuroleptique** [comment]
Found another bug in this implementation which prevent user from signing up and save data to user model
