### ISSUE TITLE
Passport version 0.6 not compatible with current express-session package

### ISSUE THREAD

**Issue by Neuroleptique** [Neuroleptique/Medical-Tracker#10]
**Describe the bug**
 When upgrading Passport version to 0.6, it will throw "req.session.regenerate is not a function".

**To Reproduce**
update passport version from 0.5.3 to 0.6.0(newest)

**Expected behavior**
Throw "req.session.regenerate is not a function" error whenever authentication is required.

![passporterror](https://user-images.githubusercontent.com/102274095/223218957-351e8769-8351-4bf7-abdb-69c7fb2dc2e6.jpg)
